client/src/axios/POST.tsx, client/src/components/searchResult/ContentSearch.tsx, client/src/pages/search.tsx
=> [FE] 검색 페이지 레이아웃

client/src/axios/dashBoardApi.tsx, client/src/features/MainGraph/components/Graph/Graph.tsx, client/src/features/MainGraph/components/MainGraph/MainGraph.tsx, client/src/features/MainGraph/hooks/useGraph.tsx, client/src/pages/dashboard.tsx
=> [FE] 대쉬보드 페이지 컴포넌트 분리 및 디렉토리 수정

client/src/components/LogoutBtn.tsx, client/src/components/UserModal.tsx, client/src/pages/dashboard.tsx, client/src/pages/index.tsx, client/src/pages/login.tsx, client/src/pages/signup.tsx, server/routes/login.js, server/routes/signup.js
일반 회원 가입 로그인 기능
비밀번호 암호화 db저장은 추후에 해야 할듯!
=> [FE/BE] 일반 로그인 로그아웃 기능 구현

client/src/pages/search.tsx, server/index.js
=> [FE] 검색 결과 갯수

client/src/features/Dashboard/components/MainGraph.tsx, client/src/features/User/LoginButton.tsx, server/db/userQueries.js, server/index.js, server/routes/myInfo.js, server/routes/tag.js, server/routes/user.js
🐞 Bug Fixes
404 Not Found error
❗️ Todo
폴더 구조 변경
태그 병합 쿼리 수정
작업 시간
3h
=> [BE] 태그병합 

server/index.js
=> [Fix Error] Fix searchRouter Error

client/src/axios/dashBoardApi.tsx, client/src/features/MainCard/components/Card.tsx, client/src/features/MainCard/hook/useCard.tsx, client/src/features/MainGraph/components/Graph/Graph.tsx, client/src/features/User/LoginButton.tsx, client/src/pages/search.tsx, client/src/pages/searchContent.tsx, client/src/pages/searchTag.tsx, client/src/recoil/atoms/MainGraphAtom.tsx
=> [FE] 빌드 에러 해결

server/db/cardQueries.js, server/db/searchQueries.js, server/db/userQueries.js, server/index.js, server/middlewares/cardCopy.js, server/routes/search.js, server/routes/uploads.js
FileTag 테이블을 드랍하여 관련 쿼리들을 수정하였습니다. 
정삭 작동 확인했습니다.
=> [BE] DB 변경에 따른 쿼리수정

server/routes/graphs.js
=> [BE] 그래프 중복 제거

server/routes/graphs.js
🐞 Bug Fixes
간선 분류 필요
❗️ Todo
간선끼리 나눌 수 있는 category추가
예상 작업 시간
4h
=> [BE] 그래프조회

server/db/followQueries.js, server/db/socialQueries.js, server/index.js, server/middlewares/cardInfo.js, server/middlewares/follow.js, server/middlewares/recomCard.js, server/middlewares/recomUser.js, server/routes/social.js
친구 추천 조회
카드 추천 조회
추천카드 거절
팔로잉 등록 
팔로잉 취소
=> feat: 소셜 기능 추가

client/package-lock.json, server/routes/graphs.js
=> [BE] 그래프 조회

README.md, client/src/features/User/GoogleLogoutBtn.tsx, client/src/features/User/SwithToggle.tsx, client/src/features/User/UserModal.tsx, client/src/features/User/WithdrawalBtn.tsx, client/src/pages/index.tsx, server/routes/login.js, server/routes/mypage.js
모달창 마이페이지 이름 수정
닉네임 수정
<br />
탈퇴
<br />
모달창
=> [FE/BE] Add 알림바, 탈퇴버튼 - #81

server/routes/user.js
=> [BE] 프로필 조회

client/src/features/Dashboard/components/NavBar.tsx
=> [FE] 설정 모달창 최상단 노출 버그 수정

client/src/features/Search/ContentSearch.tsx, client/src/pages/search.tsx, client/src/pages/searchContent.tsx, client/src/pages/searchTag.tsx
=> [FE] 검색 결과 하이라이팅

client/src/features/MainCard/components/Card.tsx, server/middlewares/cardUpdate.js
=> [FE] 카드 수정

client/src/features/User/LogoutBtn.tsx, client/src/pages/index.tsx, client/src/pages/login.tsx, client/src/pages/signup.tsx, server/routes/login.js, server/routes/signup.js
[QA]  로그인, 회원가입
redirect 속도 느리고, 비밀번호 암호화 추후에 해야함.
=> [QA]  로그인, 회원가입

client/src/pages/index.tsx, client/src/pages/login.tsx, server/routes/login.js
=> [BE] 로그인 유저 아이디 전달

client/src/features/ImageUpload/ImageUpload.tsx
=> [FE] 이미지 리사이징(canvas)

client/src/features/Dashboard/components/NavBar.tsx, client/src/pages/_app.tsx
내 그래프 공유하기
이미지 html 캡처 url 2000자 이상이라 url 압축하는 API(Bit.ly, imgur) 사용해야 함. 이러려면 도메인(https://) 필요
또한 대시보드 창에서만 공유하기 버튼을 활성화해야 함.
현재 로그인한 회원만 다른사람의 그래프 보는데 가능함 (/dashboard/{userId}) 따라서, 만약 링크로 그래프 보게 한다면, 공유용 페이지(토큰없이도 볼수 있는) 따로 만들어야 함.!
=> [FE]내 그래프 공유하기

client/.gitignore, client/package.json, client/src/features/MainGraph/components/Graph/Graph.tsx
=> [FE] 그래프 수정

client/package-lock.json, server/index.js, server/package-lock.json, server/package.json, server/routes/graphs.js, server/routes/notification.js, server/routes/user.js
=> [BE] 다른사람 정보 조회

server/middlewares/userProfile.js, server/package.json
=> [BE] logger

server/db/userQueries.js, server/middlewares/otherInfo.js, server/middlewares/userInfo.js
=> [BE] 유저정보조회 수정

server/db/userQueries.js, server/middlewares/userInfo.js
ex) Todo 생성 기능
1. 회원가입후 유저 정보 안뜸
/dashboard/:userid 다른 사람 그래프 뜨는거 안뜸..오류 발견
=> [BE] 회원가입 후, 유저 정보 오류 - #178

client/src/features/MainGraph/components/Interaction/AnimateCombineNodes.tsx, client/src/features/MainGraph/components/OnClickEvent/MouseDown.tsx
=> [FE] 병합 시 간선이 모두 끊기는 문제 수정

server/db/socialQueries.js, server/db/tagQueries.js, server/index.js, server/middlewares/cardCopy.js, server/middlewares/cardTag.js, server/middlewares/recomCard.js, server/middlewares/recomUser.js, server/routes/social.js, server/routes/z_dummy_category.js
=> [BE] DB 쿼리 구조 개선

server/db/cardQueries.js, server/middlewares/cloneCard.js
- 소셜 피드에서 + 버튼 누르면 내 그래프로 카드 자동 복사
- 복사한 태그들끼리 그래프에서 연결 관계 생성, 유지
=> [BE] 소셜 피드에서 카드 자동복사 기능 수정

server/middlewares/cloneCard.js
const에 object를 할당하여 object의 멤버필드의 값을 변경하는 방식 -> 변수를 그냥 let으로 선언
=> refactor(cloneCard.js): 변수 선언 방식 변경 -#185

client/src/features/Dashboard/MainGraph/components/Graph/Graph.tsx, client/src/features/Dashboard/MainGraph/components/MainGraph/MainGraph.tsx, client/src/features/Dashboard/components/Dashboardlayout.tsx, client/src/features/ImageUpload/ImageUpload.tsx, client/src/pages/dashboard/index.tsx, client/src/types/dashborad.types.tsx
=> [FE] 병합 및 빌드 오류 수정

server/index.js, server/winston/logger.js
=> [BE] 메소드와 응답시간도 로깅하도록 수정 -#196

server/db/userQueries.js, server/middlewares/otherInfo.js
=> [BE] 다른유저 정보 조회

client/src/features/User/SwithToggle.tsx, client/src/features/User/UserModal.tsx
=> [FE] 설정 모달 전체 수정 

server/routes/graphs.js
=> [FE] 노드 크기 수정

server/routes/graphs.js
=> [BE] 노드 인덱스 수정

client/src/features/Dashboard/MainCard/components/Card.tsx, client/src/features/Social/components/CardDetail.tsx
=> [FE] 소셜 상세 모달 디자인 수정

server/middlewares/cloneCard.js
fix: newFileId를 const에서 let으로 변경
=> fix: newFileId를 const에서 let으로 변경

client/src/pages/search.tsx, server/db/searchQueries.js, server/routes/search.js
=> [BE] 검색 페이지네이션

client/src/features/Search/CardModal.module.css, client/src/features/Search/CardModal.tsx, server/middlewares/auth-middleware.js
=> [FE] 검색페이지 카드 상세 css적용

client/src/features/Dashboard/MainGraph/components/Loading/UploadLoading.tsx, client/src/features/MainGraph/components/Loading/UploadLoading.tsx, client/src/features/Search/CardModal.tsx, client/src/features/Social/components/CardDetail.tsx, client/src/features/Social/components/Feeds.tsx, client/src/features/Social/components/Friends.tsx, client/src/features/Social/components/Users.tsx, client/src/features/User/SwithToggle.tsx, client/src/features/User/UserModal.tsx, client/src/pages/search.tsx, client/src/types/social.types.tsx, server/db/cardQueries.js, server/middlewares/cardInfo.js
=> [FE] 소셜 페이지 디자인 수정 및 코드 정리

client/src/axios/dashBoardApi.tsx, client/src/features/Dashboard/MainCard/components/Card.tsx, client/src/features/Dashboard/MainCard/components/CardPanel.tsx, client/src/features/Dashboard/MainCard/hook/useCard.tsx, client/src/types/dashborad.types.tsx, server/db/searchQueries.js, server/db/tagQueries.js, server/middlewares/cardTag.js, server/routes/search.js
=> [FE/BE] 대시보드 페이지네이션

client/src/features/Dashboard/components/NavBar.tsx
=> feat: 카카오톡 공유하기 링크 수정 - #143

server/middlewares/cloneCard.js, server/routes/notification.js
=> [BE] 복제시 알림

client/src/features/Dashboard/MainGraph/components/Graph/ChartDefaultOptions.tsx, client/src/pages/login.tsx, client/src/pages/signup.tsx
=> [FE] 회원가입, 로그인 디자인 수정

client/package.json, client/src/features/Search/CardModal.tsx, client/src/features/Search/SearchBar.tsx, client/src/pages/search.tsx
=> [FE] 검색페이지 CSS 변경

server/package.json, server/routes/login.js, server/routes/signup.js
=> [BE] 비밀번호 암호화 - #272

server/services/generate.js
프롬프트 수정
https://github.com/insight-LINK/insightLINK/issues/282
=> fix: 태그를 2개 추출하도록 프롬프트 변경

client/src/features/Dashboard/UserPanal/components/SearchBar.tsx, client/src/features/Dashboard/components/Dashboardlayout.tsx, client/src/features/Dashboard/components/NavBar.tsx, client/src/features/Search/SearchBar.tsx, client/src/features/User/LoginBtn.tsx, client/src/features/User/SignupButton.tsx, client/src/pages/index.tsx
=> [FE] Add 공유하기 페이지 및 대시보드 검색창 css 수정 - #143

server/middlewares/auth-middleware.js
=> error 메세지 수정
